#!/bin/bash
set -euo pipefail

if [[ $# != 4 ]]; then
	echo "Usage: $0 <email> <name surname> <where> <passphrase>"
	exit
fi

cd "$(dirname "$0")"
rm client.p12 client.csr client.pem client.key client.crt || true

CONF_TEMPL=client.cnf.template
OUTDIR=$(mktemp -d)
OUTZIP=$OUTDIR/develer_lan_crt.zip
LOG=$OUTDIR/openssl.log

# remove slashes in input
EMAIL=${1//\//-}
NAME=${2//\//-}
WHERE=${3//\//-}
PASSPHRASE=${4//\//-}

sed -e "s/%EMAIL%/$EMAIL/" -e "s/%NAME%/$NAME/" -e "s/%WHERE%/$WHERE/" -e "s/%PASSPHRASE%/$PASSPHRASE/" $CONF_TEMPL >client.cnf

make client.pem >"$LOG" 2>&1

if [[ $? != 0 ]]; then
	if grep -q "TXT_DB error number 2" "$LOG"; then
		echo error: identical certificate already created
	else
		echo error: look in "$LOG"
	fi
	exit 1
fi

zip "$OUTZIP" ca.pem client.crt client.p12 >/dev/null
cp ca.pem server.der client.p12 "$OUTDIR"

echo zip: "$OUTZIP"
echo ca: "$OUTDIR/ca.pem"
echo server: "$OUTDIR/server.der"
echo client: "$OUTDIR/client.p12"
