#!/bin/bash
set -euo pipefail

if [[ $# != 5 ]]; then
	echo "Usage: $0 <email> <name surname> <where> <passphrase> <output_dir>"
	exit
fi

cd "$(dirname "$0")"
make clean >/dev/null 2>&1

# remove slashes in input
EMAIL=${1//\//-}
NAME=${2//\//-}
WHERE=${3//\//-}
PASSPHRASE=${4//\//-}
OUTDIR=$5

OUTZIP=$OUTDIR/$EMAIL.zip
LOG=$OUTDIR/openssl.log


sed -e "s/%EMAIL%/$EMAIL/" -e "s/%NAME%/$NAME/" -e "s/%WHERE%/$WHERE/" -e "s/%PASSPHRASE%/$PASSPHRASE/" client.cnf.template >client.cnf

set +e
make client.pem >"$LOG" 2>&1

if [[ $? != 0 ]]; then
	if grep -q "TXT_DB error number 2" "$LOG"; then
		echo error: identical certificate already created
	else
		echo error: look in "$LOG"
	fi
	exit 1
fi
set -e

zip "$OUTZIP" ca.pem client.crt client.p12 >/dev/null
cp ca.pem server.der client.p12 "$OUTDIR"

make clean
c_rehash . >/dev/null 2>&1

echo zip: "$OUTZIP"
echo ca: "$OUTDIR/ca.pem"
echo server: "$OUTDIR/server.der"
echo client: "$OUTDIR/client.p12"
